# Generated by Django 5.0 on 2023-12-19 09:06

import django.db.models.deletion
import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotel_management", "0002_remove_room_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_rate", models.FloatField()),
                ("count_rooms", models.IntegerField()),
                ("amount_of_occupied", models.IntegerField()),
                (
                    "hotel_occupancy_percentage",
                    models.GeneratedField(
                        db_persist=True,
                        expression=django.db.models.expressions.CombinedExpression(
                            django.db.models.expressions.CombinedExpression(
                                models.F("amount_of_occupied"), "*", models.Value(100)
                            ),
                            "/",
                            models.F("count_rooms"),
                        ),
                        output_field=models.FloatField(),
                    ),
                ),
                ("generated", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_management.hotel",
                    ),
                ),
            ],
        ),
    ]
