# Generated by Django 5.0 on 2023-12-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_management", "0002_remove_room_status"),
        ("reports", "0002_remove_hotelreport_hotel_hotelreport_hotel_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_of_booking", models.IntegerField()),
                ("avg_rate", models.FloatField()),
                ("next_arrival", models.DateField()),
                ("generated", models.DateTimeField(auto_now=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_management.hotel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hotel_management.room",
                    ),
                ),
            ],
        ),
    ]
