# Generated by Django 5.0 on 2023-12-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0003_roomreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomreport",
            name="amount_of_booking",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roomreport",
            name="avg_rate",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="roomreport",
            name="next_arrival",
            field=models.DateField(blank=True, null=True),
        ),
    ]
