# Generated by Django 5.0 on 2023-12-20 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_hotelreport_count_discounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelreport",
            name="avg_rate",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
