# Generated by Django 5.0 on 2023-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0006_alter_hotelreport_avg_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=256)),
                ("count_booking", models.PositiveIntegerField()),
                ("avg_duration", models.DateField(blank=True, null=True)),
                ("popular_countries", models.CharField(max_length=10, null=True)),
                ("amount_of_occupied", models.IntegerField()),
                ("generated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
