# Generated by Django 5.0 on 2023-12-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0007_bookingreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bookingreport",
            name="avg_duration",
        ),
        migrations.AddField(
            model_name="bookingreport",
            name="duration_avg",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
