# Generated by Django 5.0 on 2023-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_remove_bookingreport_avg_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingreport",
            name="hotel_name",
            field=models.CharField(default="hotel", max_length=256),
        ),
    ]
