# Generated by Django 5.0 on 2023-12-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0009_alter_bookingreport_hotel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingreport",
            name="popular_countries",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
