# Generated by Django 5.0 on 2023-12-18 12:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotel_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="status",
        ),
    ]
