repos:
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.2.0
      hooks:
        - id: conventional-pre-commit
          stages: [ commit-msg ]
          args: [ --strict, feat, fix, chore, test, custom, docs ]
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
    - repo: https://github.com/psf/black
      rev: 23.11.0
      hooks:
        - id: black
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.3.5
      hooks:
        - id: ruff
    - repo: https://github.com/PyCQA/bandit
      rev: '1.7.8'
      hooks:
        - id: bandit
          args: [ "-x", 'tests.py', "-r", "backend" ]
          additional_dependencies: [ "bandit[toml]" ]
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
          args: ["--profile", "black"]
          name: isort (python)
