# Generated by Django 4.2.7 on 2023-12-05 14:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_remove_booking_duration_alter_booking_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="check_in",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="check_out",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(
                default=uuid.UUID("c853c144-cfde-4060-858d-06921dba43f6"),
                max_length=250,
            ),
        ),
    ]
