# Generated by Django 4.2.7 on 2023-12-05 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0003_alter_booking_check_in_alter_booking_check_out_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(
                default=uuid.UUID("1ca3fed4-a225-4dee-b79d-c15c06f0d645"),
                max_length=250,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("Reserved", "Reserved"), ("Canceled", "Canceled")],
                default="Reserved",
                max_length=20,
            ),
        ),
    ]
