# Generated by Django 4.2.7 on 2023-12-05 16:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0004_alter_booking_reservation_id_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(
                default=uuid.UUID("16b42ec4-491e-4fed-ab1e-05b128c55c8b"),
                max_length=250,
            ),
        ),
    ]
