# Generated by Django 4.2.7 on 2023-12-05 20:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0005_alter_booking_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(
                default=uuid.UUID("872568b0-ad45-4a34-a52b-2093bb9cbf99"),
                max_length=250,
            ),
        ),
    ]
