# Generated by Django 4.2.7 on 2023-12-05 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0006_alter_booking_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(
                default=uuid.UUID("9b7b96b4-b640-45fc-a37d-95a990167d34"),
                max_length=250,
            ),
        ),
    ]
