# Generated by Django 4.2.7 on 2023-12-05 22:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0007_alter_booking_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(
                default=uuid.UUID("731dd6df-a5ca-4c68-ab21-9f6d757e7450"),
                max_length=250,
            ),
        ),
    ]
