# Generated by Django 4.2.7 on 2023-12-05 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0008_alter_booking_reservation_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="reservation_id",
            field=models.CharField(max_length=250),
        ),
    ]
