# Generated by Django 5.0 on 2024-04-07 12:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.IntegerField(
                        help_text="Enter the rating for this review (1 to 5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Enter a title for this review", max_length=256
                    ),
                ),
                (
                    "comment",
                    models.TextField(help_text="Enter your comment or review here"),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(help_text="ID of the related object"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Content type of the related object",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Select the user who created this review",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
