# Generated by Django 4.2.7 on 2023-12-06 16:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="roomreview",
            old_name="hotel",
            new_name="room",
        ),
    ]
