# Generated by Django 5.0 on 2023-12-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0001_initial"),
        ("hotel_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ManyToManyField(default=list, to="hotel_management.room"),
        ),
    ]
