# Generated by Django 5.0 on 2023-12-07 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_remove_booking_room_booking_room"),
        ("hotel_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="room",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hotel_management.room",
            ),
        ),
    ]
