# Generated by Django 5.0 on 2023-12-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0004_booking_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                default="Active",
                max_length=20,
            ),
        ),
    ]
