# Generated by Django 5.0 on 2023-12-18 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0005_alter_booking_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="status",
        ),
    ]
