# Generated by Django 5.0 on 2023-12-19 15:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0006_remove_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
    ]
