# Generated by Django 5.0 on 2023-12-20 18:34

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0007_booking_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="duration",
            field=models.GeneratedField(
                db_persist=True,
                expression=django.db.models.expressions.CombinedExpression(
                    models.F("check_out"), "-", models.F("check_in")
                ),
                null=True,
                output_field=models.DurationField(),
            ),
        ),
    ]
