# Generated by Django 5.0 on 2024-04-07 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hotel_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        blank=True, help_text="Discount value", null=True
                    ),
                ),
                (
                    "percentage_value",
                    models.PositiveIntegerField(
                        blank=True, help_text="Discount percentage value", null=True
                    ),
                ),
                ("generated", models.DateField(default=datetime.date(2024, 4, 7))),
                (
                    "expiration_date",
                    models.DateField(default=datetime.date(2024, 4, 7)),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        default=list,
                        help_text="Discount rooms",
                        to="hotel_management.room",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
