# Generated by Django 5.0.4 on 2024-04-08 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hotel_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        blank=True, help_text="Discount value", null=True
                    ),
                ),
                (
                    "percentage_value",
                    models.PositiveIntegerField(
                        blank=True, help_text="Discount percentage value", null=True
                    ),
                ),
                ("generated", models.DateField(default=django.utils.timezone.now)),
                (
                    "expiration_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "rooms",
                    models.ManyToManyField(
                        default=list,
                        help_text="Discount rooms",
                        to="hotel_management.room",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
