# Generated by Django 5.0 on 2023-12-20 10:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0003_remove_discount_is_percentage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
        migrations.AddField(
            model_name="discount",
            name="generated",
            field=models.DateField(default=datetime.date(2023, 12, 20)),
        ),
    ]
