# Generated by Django 5.0 on 2023-12-20 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0004_discount_expiration_date_discount_generated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="expiration_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="discount",
            name="generated",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
