# Generated by Django 5.0 on 2023-12-21 23:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discounts", "0005_alter_discount_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="expiration_date",
            field=models.DateField(default=datetime.date(2023, 12, 22)),
        ),
        migrations.AlterField(
            model_name="discount",
            name="generated",
            field=models.DateField(default=datetime.date(2023, 12, 22)),
        ),
    ]
